# Gradle settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft / mapping / loader versions
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.3

# Mod info
mod_version=0.1.0
maven_group=com.valorantcraft
archives_base_name=valorantcraft

# Dependencies
fabric_version=0.116.13+1.21.1
